version: "3.8"
services:
  main:
    build: .
    ports:
      - "8080"
    restart: on-failure
    depends_on:
      - rabbitmq
    networks:
      - fullstack
    env_file:
      - .env
#    # Starts up 2 replicas of the same image
#    deploy:
#      replicas: 2

  rabbitmq:
    image: "rabbitmq:3.9-management-alpine"
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge